### PR TITLE
Add GPIO support

### PR DESCRIPTION
**Pull request by zvickery**
These changes add GPIO support (tested on IBR600) and fix a couple of bugs!

### CODE REVIEW

**Comment by mayfield** [comment]
Thanks Zach.

I may tweak a few things on the gpio command before doing a release but should have it out on pypi soon.

**Comment by mayfield** [comment]
Zach,

After looking at this command a bit I'm a little confused what it does (I don't have a supporting router). It seems odd to bit flip the config tree like this.  Also it might be possible through the ecm-config command already.  I'd like to understand what is really happening with this command to ensure we have the right taxonomy for it and that we're not duplicating or ignoring an opportunity to enhance a pre existing command.

Thanks,
JM

**Comment by mayfield** [comment]
Hi Zach,

After reviewing this feature with a firmware team employee I'm leaning towards this functionality just being accessed through the 'config' command.  That command (config) could use a lot of work to make it a valid replacement though, so I'm going to put some work into it and hopefully address the need.  Let me know if you think this is off base.

Thanks again for your contribution;  It's very much appreciated!
JM

**Comment by zvickery** [comment]
Admittedly I did code this to my specific needs (setting the output GPIO to the high and low states).  The GPIO approach was what I was familiar with and looked to be how the @flashleds@ command was implemented as well.  I did some more digging on this router feature and found the following:

The IBR600 UI `PUT`s to `/api/config/system/connector_gpio` with documents that look like `{data: {input: 0, output: 2}}`.  I think that was my original inspiration for this particular approach.

The GPIO input has three values which are not supported at all in this PR:

| Value | Meaning |
| --- | --- |
| 0 | Default/ignored |
| 1 | Input sensing |
| 2 | Router reset |

The GPIO output has four values, only two of which are supported in this PR:

| Value | Meaning |
| --- | --- |
| 0 | Default/low |
| 1 | High |
| 2 | Router running |
| 3 | Modem connected |

At the least, this PR should probably be enhanced to support all of that.

In my opinion, it would be good to support GPIO in an intuitive way.  I don't think manipulating configs directly is a good way to do that.  However if the GPIO command was implemented in terms of the config command, that seems reasonable.  I haven't looked at the config command enough to know how that might look.

**Pull request merged**
